FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY common ./common
COPY server ./server
COPY lib ./lib

RUN javac -cp "lib/mysql-connector-j.jar" -d out common/myCabInterface.java common/Ride.java server/myCabServer.java server/DatabaseManager.java

EXPOSE 1099

CMD ["java", "-cp", "out:lib/mysql-connector-j.jar", "server.myCabServer"]